# Generated by Django 6.0.1 on 2026-02-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('url', models.URLField()),
                ('photographer_id', models.PositiveBigIntegerField(help_text='ID of photographer if available', null=True)),
                ('avg_color', models.CharField(max_length=255, null=True)),
                ('src_original', models.URLField()),
                ('src_large2x', models.URLField(null=True)),
                ('src_large', models.URLField(null=True)),
                ('src_medium', models.URLField(null=True)),
                ('src_small', models.URLField(null=True)),
                ('src_portrait', models.URLField(null=True)),
                ('src_landscape', models.URLField(null=True)),
                ('src_tiny', models.URLField(null=True)),
                ('alt', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('photographer', models.CharField(max_length=255)),
                ('photographer_url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'photographers',
            },
        ),
    ]
