# Generated by Django 6.0.1 on 2026-02-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photographer_id',
            field=models.ForeignKey(help_text='ID of photographer if available', null=True, on_delete=django.db.models.deletion.CASCADE, to='photo_api.photographer'),
        ),
    ]
